### ISSUE TITLE
Update to sbt-1.1-RC1

### ISSUE THREAD

**Issue by laughedelic** [laughedelic/atom-sbt-client#5]
Default connection type is now IPC: https://github.com/sbt/sbt/pull/3742

**Comment by cquiroz** [comment]
it would be great to get this working with the newly released sbt 1.1
Can I help somehow?

**Comment by laughedelic** [comment]
@cquiroz good news! I just published [v0.2.0](https://github.com/laughedelic/atom-sbt-client/releases/tag/v0.2.0) which works with sbt-1.1 :shipit:
